spring:
  application.name: TelegramBotForPapaBlinov

  data:
    redis:
  #    host: redis
      host: localhost
      port: 6379

telegram:
  bot:
    username: BarberClan_bot
    token: ${TG_API_TOKEN}
    webhook-path: /webhook

ngrok:
  url: ${NGROK_URL}

openai:
  token: ${OPENAI_TOKEN}

notion:
  api:
    token: ${NOTION_API_TOKEN}




logging:
  level:
    org.springframework: INFO
  file:
    path: logs/
    name: logs/application.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 100

server:
  port: 8092